#!/bin/bash
source /infra/utils

set -e
set +u

cd $TARGET

# add the app to omero.web.apps
value=$(get_app_name)

# Configuration commands
config_commands=(
    "config append omero.web.apps '\"dpd_static_support\"'"
    "config append omero.web.apps '\"django_plotly_dash\"'"
    "config append omero.web.apps '\"bootstrap4\"'"
    "config append omero.web.apps '\"corsheaders\"'"
    "config append omero.web.ui.top_links '[\"Metrics\", \"omero_metrics_index\", {\"title\": \"Open app in new tab\", \"target\": \"_blank\"}]'"
    "config append omero.web.middleware '{\"index\": 0.5, \"class\": \"corsheaders.middleware.CorsMiddleware\"}'"
    "config append omero.web.middleware '{\"index\": 10, \"class\": \"corsheaders.middleware.CorsPostCsrfMiddleware\"}'"
    "config set omero.web.cors_origin_allow_all True"
    "config set omero.web.databases '{\"default\": {\"ENGINE\": \"django.db.backends.sqlite3\", \"NAME\": \"/opt/omero/web/django_plotly_dash_db\"}}'"
    "config append omero.web.middleware '{\"index\": 7, \"class\": \"django_plotly_dash.middleware.ExternalRedirectionMiddleware\"}'"
    "config append omero.web.middleware '{\"index\": 0.5, \"class\": \"whitenoise.middleware.WhiteNoiseMiddleware\"}'"
    "config append omero.web.middleware '{\"index\": 8, \"class\": \"django_plotly_dash.middleware.BaseMiddleware\"}'"
    "config append omero.web.middleware '{\"index\":0.1, \"class\": \"omero_metrics.middleware.OmeroAuth\"}'"
    "config append omero.web.ui.center_plugins '[\"Metrics View\", \"omero_metrics/webclient_plugins/center_plugin.metricsview.js.html\", \"metrics_view_panel\"]'"
)
su - omero-web -c "env OMERODIR=$OMERODIR /opt/omero/web/venv3/bin/omero config set omero.web.apps '[\"$value\"]'"
# Execute each configuration command
for cmd in "${config_commands[@]}"; do
    su - omero-web -c "env OMERODIR=$OMERODIR /opt/omero/web/venv3/bin/omero $cmd"
done

